version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: papiton-postgres
    environment: # Konfigurasi database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports: # Port yang digunakan untuk koneksi ke database
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Direktori penyimpanan data database
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql # Skrip pembuat 7 database
    networks:
      - papiton-network 

  # Apache kafka (KRaft mode - tanpa zookeper)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: papiton-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LIVENESS_PROBE_INTERVAL_MS: 1000
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk' # Generated ID unik untuk cluster KRaft
    networks:
      - papiton-network