// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/warehouses": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "List all warehouses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Warehouse"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Register a new warehouse",
                "parameters": [
                    {
                        "description": "Create Warehouse Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateWarehouseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Warehouse"
                        }
                    }
                }
            }
        },
        "/warehouses/movements": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Record package scan movement (IN/OUT) and return routing instructions",
                "parameters": [
                    {
                        "description": "Record Movement Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateMovementRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.MovementResponse"
                        }
                    }
                }
            }
        },
        "/warehouses/routes": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warehouses"
                ],
                "summary": "Register a static route rule",
                "parameters": [
                    {
                        "description": "Create Route Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateRouteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.WarehouseRoute"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateMovementRequest": {
            "type": "object",
            "required": [
                "orderId",
                "type",
                "warehouseId"
            ],
            "properties": {
                "destinationCity": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "orderId": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "WAREHOUSE_IN",
                        "WAREHOUSE_OUT"
                    ]
                },
                "warehouseId": {
                    "type": "string"
                }
            }
        },
        "dto.CreateRouteRequest": {
            "type": "object",
            "required": [
                "destinationCity",
                "originWarehouseId"
            ],
            "properties": {
                "destinationCity": {
                    "type": "string"
                },
                "nextWarehouseId": {
                    "type": "string"
                },
                "originWarehouseId": {
                    "type": "string"
                }
            }
        },
        "dto.CreateWarehouseRequest": {
            "type": "object",
            "required": [
                "city",
                "name"
            ],
            "properties": {
                "city": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.MovementResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "movementId": {
                    "type": "string"
                },
                "nextWarehouseId": {
                    "type": "string"
                },
                "orderId": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "warehouseId": {
                    "type": "string"
                }
            }
        },
        "models.Warehouse": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.WarehouseRoute": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "destinationCity": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nextWarehouseId": {
                    "type": "string"
                },
                "originWarehouseId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8085",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Papiton Express - Warehouse Service API",
	Description:      "REST API for Papiton Express Warehouse Service (Milestone 1)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
